# تصحيح الأخطاء (flase -> false)
org.gradle.configuration-cache=false
org.gradle.jvm.toolchain.install=true
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.fromEnv=JAVA_HOME
# إعدادات تحسين الأداء
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.daemon=false
# إعدادات الإنترنت والاتصال
systemProp.http.keepAlive=true
systemProp.https.keepAlive=true
systemProp.http.maxConnections=20