#ArchiveManager Configuration
#Thu Sep 03 00:39:58 EEST 2026
backend.path=
backend.port=8080
pg.bin=/home/safwat055/apps/postgresql/bin
pg.data=/home/safwat055/apps/postgresql/data
pg.folder=/home/safwat055/apps/postgresql
pg.port=5432
