#ArchiveManager Configuration
#Thu Sep 03 21:24:00 EEST 2026
backend.path=/run/media/safwat055/DIV Linux/projects/hr-mate/build/package/HR_MATE/bin/HR_MATE
backend.port=8080
pg.bin=/home/safwat055/apps/postgresql/bin
pg.data=/home/safwat055/apps/postgresql/data
pg.folder=/home/safwat055/apps/postgresql
pg.port=5432
